{{- if not .Values.prometheusRules.ruleGroups.customrules }}
groups: []
{{- else -}}
groups:
- name: customrules
  rules:
  - record: objectstore_bytes_received_total
    expr: |
      sum by (bucket,project_id) (
        label_replace(
          radosgw_bytes_received,
          "project_id", "$1",
          "tenant", "(.*)"
        )
      )
  - record: objectstore_bytes_sent_total
    expr: |
      sum by (bucket,project_id) (
        label_replace(
          radosgw_bytes_sent,
          "project_id", "$1",
          "tenant", "(.*)"
        )
      )
  - record: objectstore_read_ops_total
    expr: |
      sum by (bucket,project_id) (
        label_replace(
          radosgw_total_requests{method="GET"},
          "project_id", "$1",
          "tenant", "(.*)"
        )
      )
  - record: objectstore_write_ops_total
    expr: |
      sum by (bucket,project_id) (
        label_replace(
          radosgw_total_requests{method=~"PUT|POST"},
          "project_id", "$1",
          "tenant", "(.*)"
        )
      )
  - record: objectstore_capacity_usage_bytes
    expr: |
      max by (bucket,project_id) (
        label_replace(
          radosgw_usage_bucket_size, 
          "project_id", "$1", 
          "owner", "([a-f0-9]{32}).*"
        )
      )
  - record: objectstore_usage_objects
    expr: |
      max by(bucket,project_id) (
        label_replace(
          radosgw_usage_bucket_objects, 
          "project_id", "$1", 
          "owner", "([a-f0-9]{32}).*"
        )
      )
  # Client I/O Latency (GET+PUT) – avg over 5 m, in seconds
  - record: objectstore_client_io_latency_seconds_avg
    expr: |
      sum by (bucket,project_id) (
        label_replace(
          rate(radosgw_requests_duration_sum{method=~"GET|PUT"}[5m]),
          "project_id", "$1", "tenant", "(.*)"
        )
      )
      /
      sum by (bucket,project_id) (
        label_replace(
          rate(radosgw_requests_duration_count{method=~"GET|PUT"}[5m]),
          "project_id", "$1", "tenant", "(.*)"
        )
      )
  # Upload Object Latency (PUT+POST) – avg over 5 m, in ms
  - record: objectstore_upload_latency_milliseconds_avg
    expr: |
      (
        sum by (bucket,project_id) (
          label_replace(
            rate(radosgw_requests_duration_sum{method=~"PUT|POST"}[5m]),
            "project_id", "$1", "tenant", "(.*)"
          )
        )
        /
        sum by (bucket,project_id) (
          label_replace(
            rate(radosgw_requests_duration_count{method=~"PUT|POST"}[5m]),
            "project_id", "$1", "tenant", "(.*)"
          )
        )
      ) * 1000
  # Download Object Latency (GET) – avg over 5 m, in ms
  - record: objectstore_download_latency_milliseconds_avg
    expr: |
      (
        sum by (bucket,project_id) (
          label_replace(
            rate(radosgw_requests_duration_sum{method="GET"}[5m]),
            "project_id", "$1", "tenant", "(.*)"
          )
        )
        /
        sum by (bucket,project_id) (
          label_replace(
            rate(radosgw_requests_duration_count{method="GET"}[5m]),
            "project_id", "$1", "tenant", "(.*)"
          )
        )
      ) * 1000
  # Delete Object Latency (DELETE) – avg over 5 m, in ms
  - record: objectstore_delete_latency_milliseconds_avg
    expr: |
      (
        sum by (bucket,project_id) (
          label_replace(
            rate(radosgw_requests_duration_sum{method="DELETE"}[5m]),
            "project_id", "$1", "tenant", "(.*)"
          )
        )
        /
        sum by (bucket,project_id) (
          label_replace(
            rate(radosgw_requests_duration_count{method="DELETE"}[5m]),
            "project_id", "$1", "tenant", "(.*)"
          )
        )
      ) * 1000
  # Client Error Rate (4xx) – per second, per bucket & error
  - record: objectstore_client_error_rate
    expr: |
      sum by (bucket,project_id,http_status) (
        label_replace(
          rate(radosgw_http_errors_by_user{http_status=~"4.."}[5m]),
          "project_id", "$1", "tenant", "([a-f0-9]{32})"
        )
      )
  # Server / Service Error Rate (5xx) – per second, per bucket & error
  - record: objectstore_server_error_rate
    expr: |
      sum by (bucket,project_id,http_status) (
        label_replace(
          rate(radosgw_http_errors_by_user{http_status=~"5.."}[5m]),
          "project_id", "$1", "tenant", "([a-f0-9]{32})"
        )
      )
{{- end }}
