{{- if not .Values.prometheusRules.ruleGroups.generic }}
groups: []
{{- else -}}
groups:
- name: generic
  rules:
{{- if not (.Values.prometheusRules.disabled.CephDaemonCrash | default false) }}
  - alert: CephDaemonCrash
    expr: ceph_health_detail{name="RECENT_CRASH"} == 1
    for: 1m
    labels:
      oid: "1.3.6.1.4.1.50495.1.2.1.1.2"
      severity: critical
      type: ceph_default
      {{- include "cloud-storage-operations.additionalRuleLabels" . | nindent 6 }}
    annotations:
      description: "One or more daemons have crashed recently, and need to be acknowledged. This notification ensures that software crashes do not go unseen. To acknowledge a crash, use the 'ceph crash archive <id>' command."
      documentation: "https://docs.ceph.com/en/latest/rados/operations/health-checks/#recent-crash"
      summary: "One or more Ceph daemons have crashed, and are pending acknowledgement"
{{- end }}

{{- if not (.Values.prometheusRules.disabled.PrometheusJobMissing | default false) }}
  - alert: "PrometheusJobMissing"
    expr: "absent(up{job=\"rook-ceph-mgr\"})"
    for: "30s"
    labels:
      oid: "1.3.6.1.4.1.50495.1.2.1.12.1"
      severity: "critical"
      type: "ceph_default"
    annotations:
      description: "The prometheus job that scrapes from Ceph MGR is no longer defined, this will effectively mean you'll have no metrics or alerts for the cluster.  Please review the job definitions in the prometheus.yml file of the prometheus instance."
      summary: "The scrape job for Ceph MGR is missing from Prometheus"
{{- end }}

{{- if not (.Values.prometheusRules.disabled.PrometheusJobExporterMissing | default false) }}
  - alert: "PrometheusJobExporterMissing"
    expr: "sum(absent(up{job=\"rook-ceph-exporter\"})) and sum(ceph_osd_metadata{ceph_version=~\"^ceph version (1[89]|[2-9][0-9]).*\"}) > 0"
    for: "30s"
    labels:
      oid: "1.3.6.1.4.1.50495.1.2.1.12.1"
      severity: "critical"
      type: "ceph_default"
    annotations:
      description: "The prometheus job that scrapes from Ceph Exporter is no longer defined, this will effectively mean you'll have no metrics or alerts for the cluster.  Please review the job definitions in the prometheus.yml file of the prometheus instance."
      summary: "The scrape job for Ceph Exporter is missing from Prometheus"
{{- end }}
{{- end }}
