# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and cobaltcore-dev contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: greenhouse.sap/v1alpha1
kind: PluginDefinition
metadata:
  name: ceph-operations
spec:
  version: "1.0.1"
  displayName: Ceph operations bundle
  description: Operations bundle for the Ceph storage backend
  docMarkDownUrl: https://raw.githubusercontent.com/cobaltcore-dev/cloud-storage-operations/main/ceph-operations/README.md
  icon: https://raw.githubusercontent.com/cobaltcore-dev/cloud-storage-operations/main/ceph-operations/ceph-logo.png
  helmChart:
    name: ceph-operations
    repository: oci://ghcr.io/cobaltcore-dev/ceph-operations/charts
    version: 1.0.1
