{
 "title": "ceph rgw api usage",
 "tags": [ "ceph" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(radosgw_user_metadata, job)"
    }
   },
   {
    "name": "user",
    "query": {
     "query": "label_values(radosgw_user_metadata, user)"
    }
   },
   {
    "name": "bucket",
    "query": {
     "query": "label_values(radosgw_bucket_capacity_usage_bytes, bucket)"
    }
   },
   {
    "name": "api_category",
    "query": {
     "query": "label_values(radosgw_api_usage_per_user_per_sec, api_category)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "API Usage Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(radosgw_api_usage_per_user_total_per_sec{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "API Usage Total"
    }
   ]
  },
  {
   "title": "API Usage Total Per User",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(radosgw_api_usage_per_user_total_per_sec{job=~\"$job\", user=~\"$user\"}[$__rate_interval])",
     "legendFormat": "{{ user }}"
    }
   ]
  },
  {
   "title": "API Usage Total Per Bucket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(radosgw_bucket_api_usage_total_per_sec{job=~\"$job\", bucket=~\"$bucket\"}[$__rate_interval])",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "API Usage Total Per Category",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (api_category) (rate(radosgw_api_usage_per_user_per_sec{job=~\"$job\", api_category=~\"$api_category\"}[$__rate_interval]))",
     "legendFormat": "{{ api_category }}"
    }
   ]
  },
  {
   "title": "API Usage Per Category Per User",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(radosgw_api_usage_per_user_per_sec{job=~\"$job\", user=~\"$user\", api_category=~\"$api_category\"}[$__rate_interval])",
     "legendFormat": "{{ api_category }} - {{ user }}"
    }
   ]
  },
  {
   "title": "API Usage Per Category Per Bucket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(radosgw_bucket_api_usage_per_sec{job=~\"$job\", bucket=~\"$bucket\", category=~\"$api_category\"}[$__rate_interval])",
     "legendFormat": "{{ category }} - {{ bucket }}"
    }
   ]
  }
 ]
}