{
 "title": "ceph rgw overview",
 "tags": [ "ceph" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(radosgw_user_metadata, job)"
    }
   },
   {
    "name": "user",
    "query": {
     "query": "label_values(radosgw_user_metadata, user)"
    }
   },
   {
    "name": "bucket",
    "query": {
     "query": "label_values(radosgw_bucket_capacity_usage_bytes, bucket)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RGW Status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(ceph_rgw_metadata{})", "legendFormat": "Up" },
    {
     "expr": "count(ceph_rgw_metadata{}) - sum(ceph_rgw_metadata{})",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Used Cluster Capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes{}",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Used Cluster Capacity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes{} / ceph_cluster_total_bytes{}"
    }
   ]
  },
  {
   "title": "Cluster Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(radosgw_cluster_throughput_bytes_per_sec{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ rgw_cluster_id }}"
    }
   ]
  },
  {
   "title": "Available Cluster Capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "ceph_cluster_total_bytes{}", "legendFormat": "{{ cluster }}" }
   ]
  },
  {
   "title": "Available Cluster Capacity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ceph_cluster_total_bytes{} - ceph_cluster_total_used_bytes{}) / ceph_cluster_total_bytes{}"
    }
   ]
  },
  {
   "title": "Cluster Reads/Writes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(radosgw_cluster_reads_per_sec{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Read OPs"
    },
    {
     "expr": "rate(radosgw_cluster_writes_per_sec{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Write OPs"
    }
   ]
  },
  {
   "title": "Objects in the Cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (ceph_pool_objects) by (pool_id)",
     "legendFormat": "pool id {{ pool_id }}"
    }
   ]
  },
  {
   "title": "Cluster Total OPs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(radosgw_cluster_ops_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ rgw_cluster_id }}"
    }
   ]
  },
  {
   "title": "Current Cluster OPs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(radosgw_cluster_ops_per_sec{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ rgw_cluster_id }}"
    }
   ]
  },
  {
   "title": "Data Sent / Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(radosgw_cluster_bytes_sent_per_sec{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Data Sent"
    },
    {
     "expr": "rate(radosgw_cluster_bytes_received_per_sec{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Data Received"
    }
   ]
  },
  {
   "title": "Total Data Downloaded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 13, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radosgw_cluster_bytes_sent_total{job=\"$job\"} - (radosgw_cluster_bytes_sent_total{job=\"$job\"} @ ${__from:date:seconds})"
    }
   ]
  },
  {
   "title": "Total Data Uploaded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radosgw_cluster_bytes_received_total{job=\"$job\"} - (radosgw_cluster_bytes_received_total{job=\"$job\"} @ ${__from:date:seconds})"
    }
   ]
  },
  {
   "title": "RGW Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(ceph_rgw_get_b{}[$__rate_interval]))",
     "legendFormat": "GET"
    },
    {
     "expr": "sum(irate(ceph_rgw_put_b{}[$__rate_interval]))",
     "legendFormat": "PUT"
    }
   ]
  },
  { "title": "RGW Instance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Average GET/PUT Latencies",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(ceph_rgw_get_initial_lat_sum[$__rate_interval]) / rate(ceph_rgw_get_initial_lat_count[$__rate_interval]))",
     "legendFormat": "GET AVG"
    },
    {
     "expr": "avg(rate(ceph_rgw_put_initial_lat_sum[$__rate_interval]) / rate(ceph_rgw_put_initial_lat_count[$__rate_interval]))",
     "legendFormat": "PUT AVG"
    }
   ]
  },
  {
   "title": "Total Requests/sec by RGW Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "label_replace(\n  rate(ceph_rgw_req[$__rate_interval]),\n  \"rgw_host\", \"$1\", \"pod\", \"rook-ceph-exporter-(.*)-.*-.*\"\n)",
     "legendFormat": "{{ rgw_host }}"
    }
   ]
  },
  {
   "title": "GET Latencies by RGW Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(rate(ceph_rgw_get_initial_lat_sum[$__rate_interval]), \"rgw_host\", \"$1\", \"pod\", \"rook-ceph-exporter-(.*)-.*-.*\") / \nlabel_replace(rate(ceph_rgw_get_initial_lat_count[$__rate_interval]), \"rgw_host\", \"$1\", \"pod\", \"rook-ceph-exporter-(.*)-.*-.*\")",
     "legendFormat": "{{ rgw_host }}"
    }
   ]
  },
  {
   "title": "Request Queue Length",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(ceph_rgw_qlen)" }
   ]
  },
  {
   "title": "Bandwidth Consumed by Type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(ceph_rgw_get_b[$__rate_interval]))",
     "legendFormat": "GETs"
    },
    {
     "expr": "sum(rate(ceph_rgw_put_b[$__rate_interval]))",
     "legendFormat": "PUTs"
    }
   ]
  },
  {
   "title": "Bandwidth by RGW Instance",
   "type": "timeseries",
   "description": "Total bytes transferred in/out through get/put operations, by radosgw instance",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(rgw_host) (\n  (label_replace(rate(ceph_rgw_get_b[$__rate_interval]), \"rgw_host\", \"$1\", \"pod\", \"rook-ceph-exporter-(.*)-.*-.*\")) + \n  (label_replace(rate(ceph_rgw_put_b[$__rate_interval]), \"rgw_host\", \"$1\", \"pod\", \"rook-ceph-exporter-(.*)-.*-.*\"))\n)",
     "legendFormat": "{{ rgw_host }}"
    }
   ]
  },
  {
   "title": "PUT Latencies by RGW Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(rate(ceph_rgw_put_initial_lat_sum[$__rate_interval]), \"rgw_host\", \"$1\", \"pod\", \"rook-ceph-exporter-(.*)-.*-.*\") / \nlabel_replace(rate(ceph_rgw_put_initial_lat_count[$__rate_interval]), \"rgw_host\", \"$1\", \"pod\", \"rook-ceph-exporter-(.*)-.*-.*\")",
     "legendFormat": "{{ rgw_host }}"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 42 },
   "targets": [
    {
     "expr": "label_replace(\n  rate(ceph_rgw_failed_req[$__rate_interval]),\n  \"rgw_host\", \"$1\", \"pod\", \"rook-ceph-exporter-(.*)-.*-.*\"\n)",
     "legendFormat": "{{ rgw_host }}"
    }
   ]
  },
  {
   "title": "All GET/PUT Latencies",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(rate(ceph_rgw_get_initial_lat_sum[$__rate_interval]), \"rgw_host\", \"$1\", \"pod\", \"rook-ceph-exporter-(.*)-.*-.*\") / \nlabel_replace(rate(ceph_rgw_get_initial_lat_count[$__rate_interval]), \"rgw_host\", \"$1\", \"pod\", \"rook-ceph-exporter-(.*)-.*-.*\")",
     "legendFormat": "GET {{ rgw_host }}"
    },
    {
     "expr": "label_replace(rate(ceph_rgw_put_initial_lat_sum[$__rate_interval]), \"rgw_host\", \"$1\", \"pod\", \"rook-ceph-exporter-(.*)-.*-.*\") / \nlabel_replace(rate(ceph_rgw_put_initial_lat_count[$__rate_interval]), \"rgw_host\", \"$1\", \"pod\", \"rook-ceph-exporter-(.*)-.*-.*\")",
     "legendFormat": "PUT {{ rgw_host }}"
    }
   ]
  },
  {
   "title": "Bandwidth by HTTP Operation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(rate(ceph_rgw_get_b[$__rate_interval]), \"rgw_host\", \"$1\", \"pod\", \"rook-ceph-exporter-(.*)-.*-.*\")",
     "legendFormat": "GETs {{ rgw_host }}"
    },
    {
     "expr": "label_replace(rate(ceph_rgw_put_b[$__rate_interval]), \"rgw_host\", \"$1\", \"pod\", \"rook-ceph-exporter-(.*)-.*-.*\")",
     "legendFormat": "PUTs {{ rgw_host }}"
    }
   ]
  },
  {
   "title": "Workload Breakdown",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  rate(ceph_rgw_failed_req[$__rate_interval]),\n  \"rgw_host\", \"$1\", \"pod\", \"rook-ceph-exporter-(.*)-.*-.*\"\n)",
     "legendFormat": "Failures {{ rgw_host }}"
    },
    {
     "expr": "label_replace(\n  rate(ceph_rgw_get[$__rate_interval]),\n  \"rgw_host\", \"$1\", \"pod\", \"rook-ceph-exporter-(.*)-.*-.*\"\n)",
     "legendFormat": "GET {{ rgw_host }}"
    },
    {
     "expr": "label_replace(\n  rate(ceph_rgw_put[$__rate_interval]),\n  \"rgw_host\", \"$1\", \"pod\", \"rook-ceph-exporter-(.*)-.*-.*\"\n)",
     "legendFormat": "PUT {{ rgw_host }}"
    },
    {
     "expr": "label_replace(\n  rate(ceph_rgw_req[$__rate_interval]) -\n    (rate(ceph_rgw_get[$__rate_interval]) + rate(ceph_rgw_put[$__rate_interval])),\n  \"rgw_host\", \"$1\", \"pod\", \"rook-ceph-exporter-(.*)-.*-.*\"\n)",
     "legendFormat": "Other (DELETE,LIST) {{ rgw_host}}"
    }
   ]
  },
  {
   "title": "HTTP Request Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "label_replace(rate(ceph_rgw_failed_req[$__rate_interval]), \"rgw_host\", \"$1\", \"pod\", \"rook-ceph-exporter-(.*)-.*-.*\")",
     "legendFormat": "Requests Failed {{ rgw_host }}"
    },
    {
     "expr": "label_replace(rate(ceph_rgw_get[$__rate_interval]), \"rgw_host\", \"$1\", \"pod\", \"rook-ceph-exporter-(.*)-.*-.*\")",
     "legendFormat": "GETs {{ rgw_host }}"
    },
    {
     "expr": "label_replace(rate(ceph_rgw_put[$__rate_interval]), \"rgw_host\", \"$1\", \"pod\", \"rook-ceph-exporter-(.*)-.*-.*\")",
     "legendFormat": "PUTs {{ rgw_host }}"
    },
    {
     "expr": "label_replace(\n  rate(ceph_rgw_req[$__rate_interval]) - (rate(ceph_rgw_get[$__rate_interval]) + rate(ceph_rgw_put[$__rate_interval])),\n\"rgw_host\", \"$1\", \"pod\", \"rook-ceph-exporter-(.*)-.*-.*\")",
     "legendFormat": "Other {{ rgw_host }}"
    }
   ]
  },
  { "title": "Bucket Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Throughput Per Bucket",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(radosgw_bucket_throughput_bytes_per_sec{job=~\"$job\", bucket=~\"$bucket\"}[$__rate_interval])",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Read OPs Per Bucket",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(radosgw_bucket_read_ops_per_sec{job=~\"$job\", bucket=~\"$bucket\"}[$__rate_interval])",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Top 10 - OPs Per Bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(10, rate(radosgw_bucket_ops_per_sec{job=\"$job\"}[$__rate_interval]) > 0)",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Write OPs Per Bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(radosgw_bucket_write_ops_per_sec{job=~\"$job\", bucket=~\"$bucket\"}[$__rate_interval])",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Current OPs Per Bucket",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(radosgw_bucket_ops_per_sec{job=~\"$job\", bucket=~\"$bucket\"}[$__rate_interval])",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Top 10 - Capacity Consumers Per Bucket",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, radosgw_usage_bucket_bytes{job=\"$job\"} > 0)"
    }
   ]
  },
  {
   "title": "Objects Per Bucket",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(radosgw_usage_bucket_objects{job=~\"$job\", bucket=~\"$bucket\"} > 0)"
    }
   ]
  },
  { "title": "User Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Throughput Per User",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(radosgw_user_throughput_bytes_per_sec{user=~\"$user\", job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Write OPs Per User",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "radosgw_user_write_ops_per_sec{user=~\"$user\", job=~\"$job\"}",
     "legendFormat": "{{ user }}"
    }
   ]
  },
  {
   "title": "Current OPs Per User",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "radosgw_user_ops_per_sec{user=~\"$user\", job=~\"$job\"}",
     "legendFormat": "{{ user }}"
    }
   ]
  },
  {
   "title": "Read OPs Per User",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "radosgw_user_read_ops_per_sec{user=~\"$user\", job=~\"$job\"}",
     "legendFormat": "{{ user }}"
    }
   ]
  },
  {
   "title": "Top 10 - OPs per User",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(10, radosgw_user_ops_per_sec{job=~\"$job\"})",
     "legendFormat": "{{ user }}"
    }
   ]
  },
  {
   "title": "Top 10 - Amount Of Objects Per User",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, radosgw_user_objects_total{job=\"$job\"} > 0)"
    }
   ]
  },
  {
   "title": "Top 10 - Capacity Consumers Per User",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, radosgw_user_capacity_usage_bytes{job=\"$job\"} > 0)"
    }
   ]
  },
  {
   "title": "Top 10 - Buckets Per User",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 131 },
   "targets": [
    {
     "expr": "topk(10, radosgw_user_buckets_total{job=~\"$job\"} > 0)"
    }
   ]
  },
  {
   "title": "Total OPs Per User",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 140 },
   "targets": [
    {
     "expr": "radosgw_user_write_ops_total{user=~\"$user\", job=~\"$job\"}"
    },
    {
     "expr": "radosgw_user_read_ops_total{user=~\"$user\", job=~\"$job\"}"
    },
    {
     "expr": "radosgw_user_ops_total{user=~\"$user\", job=~\"$job\"}"
    },
    {
     "expr": "radosgw_user_success_ops_total{user=~\"$user\", job=~\"$job\"}"
    },
    {
     "expr": "radosgw_user_error_rate_total{user=~\"$user\", job=~\"$job\"}"
    }
   ]
  }
 ]
}